export const recommendationResponseSchema = {
  type: 'object',
  additionalProperties: false,
  required: ['courses'],
  properties: {
    courses: {
      type: 'array',
      minItems: 3,
      maxItems: 3,
      items: {
        type: 'object',
        additionalProperties: false,
        required: [
          'id',
          'title',
          'summary',
          'reason',
          'places',
          'totalDistanceMeters',
          'totalDurationSeconds',
          'travelDurationSeconds',
          'startTime',
          'endTime',
        ],
        properties: {
          id: { type: 'string' },
          title: { type: 'string' },
          summary: { type: 'string' },
          reason: { type: 'string' },
          places: {
            type: 'array',
            minItems: 1,
            items: {
              type: 'object',
              additionalProperties: false,
              required: [
                'order',
                'name',
                'address',
                'latitude',
                'longitude',
                'imageUrl',
                'overview',
                'homepageUrl',
                'arrivalTime',
                'category',
                'distanceFromPrevMeters',
                'durationFromPrevSeconds',
              ],
              properties: {
                order: { type: 'integer', minimum: 1 },
                name: { type: 'string' },
                address: { type: 'string' },
                latitude: { type: 'number' },
                longitude: { type: 'number' },
                imageUrl: { type: ['string', 'null'] },
                overview: { type: ['string', 'null'] },
                homepageUrl: { type: ['string', 'null'] },
                arrivalTime: { type: ['string', 'null'] },
                category: { type: ['string', 'null'] },
                distanceFromPrevMeters: { type: ['number', 'null'], minimum: 0 },
                durationFromPrevSeconds: { type: ['number', 'null'], minimum: 0 },
              },
            },
          },
          totalDistanceMeters: { type: 'number', minimum: 0 },
          totalDurationSeconds: { type: 'number', minimum: 0 },
          travelDurationSeconds: { type: ['number', 'null'], minimum: 0 },
          startTime: { type: ['string', 'null'] },
          endTime: { type: ['string', 'null'] },
        },
      },
    },
  },
} as const;
