import { HttpStatus } from '@nestjs/common';

export const COMMON_ERROR_CODES = {
  BAD_REQUEST: 'COMMON400',
  UNAUTHORIZED: 'COMMON401',
  FORBIDDEN: 'COMMON403',
  NOT_FOUND: 'COMMON404',
  METHOD_NOT_ALLOWED: 'COMMON405',
  CONFLICT: 'COMMON409',
  UNPROCESSABLE_ENTITY: 'COMMON422',
  INTERNAL_SERVER_ERROR: 'COMMON500',
  SERVICE_UNAVAILABLE: 'COMMON503',
} as const;

const statusToCode: Partial<Record<number, string>> = {
  [HttpStatus.BAD_REQUEST]: COMMON_ERROR_CODES.BAD_REQUEST,
  [HttpStatus.UNAUTHORIZED]: COMMON_ERROR_CODES.UNAUTHORIZED,
  [HttpStatus.FORBIDDEN]: COMMON_ERROR_CODES.FORBIDDEN,
  [HttpStatus.NOT_FOUND]: COMMON_ERROR_CODES.NOT_FOUND,
  [HttpStatus.METHOD_NOT_ALLOWED]: COMMON_ERROR_CODES.METHOD_NOT_ALLOWED,
  [HttpStatus.CONFLICT]: COMMON_ERROR_CODES.CONFLICT,
  [HttpStatus.UNPROCESSABLE_ENTITY]: COMMON_ERROR_CODES.UNPROCESSABLE_ENTITY,
  [HttpStatus.SERVICE_UNAVAILABLE]: COMMON_ERROR_CODES.SERVICE_UNAVAILABLE,
};

export const getCommonErrorCode = (statusCode: number): string =>
  statusToCode[statusCode] ?? COMMON_ERROR_CODES.INTERNAL_SERVER_ERROR;
